# trigger update 
 name: MLflow CI Advanced

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test workflow
        run: echo "GitHub Actions berhasil jalan"
